name: Rust

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          depth: 50
      - name: Set Rust Version
        run: rustup default ${{ matrix.channel }}
      - name: Build
        run: cargo build --target ${{ matrix.target }}
      - name: Test
        run: cargo test --target ${{ matrix.target }}

    strategy:
      fail-fast: true
      matrix:
        channel: [stable, beta, nightly]
        target:
          # Linux
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - mips-unknown-linux-gnu
          - mips64-unknown-linux-gnuabi64
          - mips64el-unknown-linux-gnuabi64
          - mipsel-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - s390x-unknown-linux-gnu # DISABLE_TESTS=1
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
